version "4.11"

// Base Classes
#include "zscript/sirus/monsters/ZombieScientist.zsc"

// Zombie Scientists
#include "zscript/sirus/monsters/FemaleCleaver.zsc"
#include "zscript/sirus/monsters/FemaleKnife.zsc"
#include "zscript/sirus/monsters/FemaleSyringe.zsc"
#include "zscript/sirus/monsters/FemaleWrench.zsc"
#include "zscript/sirus/monsters/MaleAxe.zsc"
#include "zscript/sirus/monsters/MaleCrowbar.zsc"
#include "zscript/sirus/monsters/MaleHammer.zsc"

#include "zscript/sirus/monsters/DeadScientists.zsc"

// Spawn Handler
#include "zscript/sirus/SpawnHandler.zsc"