name: Update Changelog

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Set a Release Version'
        required: true
  pull_request:
    types: [ opened ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: saadmk11/changelog-ci@v1.1.2
        with:
          release_version: ${{ github.event.inputs.release_version }}
